site_name: Lite XL

site_url: !ENV [SITE_URL, "https://takase1121.github.io/lite-xl-docs/"]
repo_url: !ENV [REPO_URL, "https://github.com/takase1121/lite-xl-docs/"]

site_description: "Lightweight and powerful code editor, available for Windows, Linux and macOS."
site_author: "takase1121 <20792268+takase1121@users.noreply.github.com>"

theme:
  name: material
  custom_dir: docs/overrides/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # no custom fonts
  font: false
  logo: assets/icon.svg
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - content.action.view
    - content.action.edit
    - header.autohide

extra_css:
  - stylesheets/extra.css
extra:
  lite_xl_version: v2.1.1
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lite-xl/lite-xl
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RWzqC3nx7K
    - icon: simple/matrix
      link: https://matrix.to/#/#lite-xl:matrix.org
  extra_key_map: {
    "\\": "backslash",
    "|": "bar",
    "[": "bracket-left",
    "]": "bracket-right",
    "{": "brace-left",
    "}": "brace-right",
    ":": "colon",
    ",": "comma",
    "\"": "double-quote",
    "=": "equal",
    "!": "exclam",
    "`": "grave",
    ">": "greater",
    "<": "less",
    "-": "minus",
    ".": "period",
    "+": "plus",
    "?": "question",
    ";": "semicolon",
    "'": "single-quote",
    "/": "slash",
    "~": "tilde",
    "_": "underscore",
    "pageup": "page-up",
    "pagedown": "page-down",
    "printscreen": "print-screen",
    "scrolllock": "scroll-lock",
    "capslock": "caps-lock",
    "keypad enter": "num-enter",
    "left gui": "left-windows",
    "lclick": "left-button",
    "rclick": "right-button",
    "mclick": "middle-button",
    "xclick": "x-button1",
    "yclick": "x-button2",
  }

plugins:
  - search
  - glightbox
  - macros:
      include_dir: docs/.include
      include_yaml:
        # yes, this can safely load json
        - keymap: docs/assets/keymap.json
        - keymap_macos: docs/assets/keymap-macos.json
  - git-revision-date-localized
  - social:
      cards: !ENV [CARDS, false]
      cards_color:
        fill: "#252529"
        text: "#e1e1e6"
      cards_font: Roboto
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      css_files:
        - assets/stylesheets/custom.css
      js_files:
        - assets/javascript/custom.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys:
      key_map: {
        "wheel": "Mouse wheel",
        "hwheel": "Horizontal mouse wheel",
        "wheelup": "Mouse wheel up",
        "wheeldown": "Mouse wheel down"
      }

nav:
  - Home: index.md
  - "Set Up":
      - "Getting Started": setup/getting-started.md
      - "Windows": setup/windows.md
      - "Linux": setup/linux.md
      - "macOS": setup/macos.md
      - "Building": setup/building.md
  - "User Guide":
      - "Introduction": user-guide/introduction.md
      - "Configuration": user-guide/configuration.md
      - "Plugins": user-guide/plugins.md
      - "Keymap": user-guide/keymap.md
      - "macOS Keymap": user-guide/macos-keymap.md
  - "Developer Guide":
      - "Creating Syntaxes": developer-guide/creating-syntaxes.md
      - "Simple Plugin": developer-guide/simple-plugin.md
      - "Using regular expressions": developer-guide/using-regular-expressions.md
      - "Interacting with the OS": developer-guide/interacting-with-the-os.md
      - "Child processes": developer-guide/child-processes.md
  - "About":
      - "Contributors": about/contributors.md
      - "FAQ": about/faq.md