site_name: Documentation for Lite XL

site_url: !ENV [SITE_URL, "https://takase1121.github.io/lite-xl-docs/"]
repo_url: !ENV [REPO_URL, "https://github.com/takase1121/lite-xl-docs/"]

site_description: Documentation for Lite XL, a text editor for Windows, Linux and macOS.
site_author: Takase

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # no custom fonts
  font: false
  logo: assets/icon.svg
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - header.autohide

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lite-xl/lite-xl
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RWzqC3nx7K
    - icon: simple/matrix
      link: https://matrix.to/#/#lite-xl:matrix.org

plugins:
  - search
  - social:
      cards: !ENV [CARDS, false]
      cards_font: Roboto

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 