[tool.poetry]
name = "lite-xl-docs"
version = "0.1.0"
description = "The website for Lite XL."
authors = ["takase1121 <20792268+takase1121@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
mkdocs-material = "^9.0.14"
Pillow = "^9.4.0"
CairoSVG = "^2.6.0"
mkdocs-git-revision-date-localized-plugin = "^1.1.0"
mkdocs-glightbox = "^0.3.1"
mkdocs-macros-plugin = "^0.7.0"
mkdocs-minify-plugin = "^0.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"