name: Deploy site

on: { push: { branches: [master] } }

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # needed for accurate dates
          fetch-depth: 0
      # environment has these deps.
      # - name: Install dependencies
      #   run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - name: Cache build data
        uses: actions/cache@v3
        with:
          key: mkdocs-cache-${{ runner.os }}-${{ hashFiles('**/poetry.lock', '**/mkdocs.yml') }}
          path: .cache
      - name: Install dependencies
        run: poetry install
      - name: Set up environment variables
        run: echo "CARDS=true" >> $GITHUB_ENV
      - name: Build and deploy
        run: poetry run mkdocs gh-deploy --force
