name: Deploy site

on: { push: { branches: [master] } }

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install mkdocs-material
        run: pip install mkdocs-material
      - name: Build and deploy
        run: mkdocs gh-deploy --force
