name: Deploy site

on: { push: { branches: [master] } }

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # needed for accurate dates
          fetch-depth: 0
      # environment has these deps.
      # - name: Install dependencies
      #   run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Cache build data
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          path: .cache
      - name: Install mkdocs-material
        run: pip install -r requirements.txt
      - name: Set up environment variables
        run: echo "CARDS=true" >> $GITHUB_ENV
      - name: Build and deploy
        run: mkdocs gh-deploy --force
